#!/usr/bin/env sh

set -eu

[ -e /opt/resource/common ] && cd /opt/resource
. ./common

filter='[
  {"digest": $version}
] | tostring'
jq -r --null-input --arg version "$(crane digest "$REPOSITORY:$TAG")" "$filter"
