#!/usr/bin/env sh

set -eu

[ -e /opt/resource/common ] && cd /opt/resource
. ./common

oci_dir="$(mktemp -d)"
crane pull --format=oci "$REPOSITORY:@$(jq -r .version "$INPUT_FILE")" "$oci_dir"
cd "$oci_dir"
tar cf "$1/image.tar" ./*
cd - 1>&2

echo "$(jq -r .version < "$INPUT_FILE")"
